export const COLORS={black:{digit:0,multiplier:0,hex:"#202124"},brown:{digit:1,multiplier:1,tolerance:1,temp:100,hex:"#795548"},red:{digit:2,multiplier:2,tolerance:2,temp:50,hex:"#d83b35"},orange:{digit:3,multiplier:3,temp:15,hex:"#ed861c"},yellow:{digit:4,multiplier:4,temp:25,hex:"#f6c944"},green:{digit:5,multiplier:5,tolerance:.5,hex:"#318052"},blue:{digit:6,multiplier:6,tolerance:.25,temp:10,hex:"#3c73b8"},violet:{digit:7,multiplier:7,tolerance:.1,temp:5,hex:"#7a4da0"},gray:{digit:8,multiplier:8,tolerance:.05,hex:"#848b92"},white:{digit:9,multiplier:9,hex:"#f4f6f5"},gold:{multiplier:-1,tolerance:5,hex:"#c59a29"},silver:{multiplier:-2,tolerance:10,hex:"#b5bbc0"}};
export const DIGIT_COLORS=Object.keys(COLORS).filter(color=>COLORS[color].digit!==undefined);
export const MULTIPLIER_COLORS=Object.keys(COLORS).filter(color=>COLORS[color].multiplier!==undefined);
export const TOLERANCE_COLORS=Object.keys(COLORS).filter(color=>COLORS[color].tolerance!==undefined);
export const TEMP_COLORS=Object.keys(COLORS).filter(color=>COLORS[color].temp!==undefined);
export const E12=[10,12,15,18,22,27,33,39,47,56,68,82];
export function formatOhms(value){const number=Number(value);if(!Number.isFinite(number))return"—";if(Math.abs(number)>=1e9)return`${trim(number/1e9)} GΩ`;if(Math.abs(number)>=1e6)return`${trim(number/1e6)} MΩ`;if(Math.abs(number)>=1e3)return`${trim(number/1e3)} kΩ`;return`${trim(number)} Ω`;}
function trim(value){return Number(value.toPrecision(6)).toString();}
function requireColor(color,field,allowed){if(!allowed.includes(color))throw new Error(`${field} color "${color}" is not valid.`);return COLORS[color];}
export function calculate(bands){if(!Array.isArray(bands)||![4,5,6].includes(bands.length))throw new Error("Provide exactly 4, 5, or 6 band colors.");const significantCount=bands.length===4?2:3,digits=bands.slice(0,significantCount).map(color=>requireColor(color,"Digit",DIGIT_COLORS).digit);if(digits[0]===0)throw new Error("The first significant digit cannot be black.");const multiplierColor=bands[significantCount],toleranceColor=bands[significantCount+1],multiplier=requireColor(multiplierColor,"Multiplier",MULTIPLIER_COLORS).multiplier,tolerance=requireColor(toleranceColor,"Tolerance",TOLERANCE_COLORS).tolerance;let temp=null;if(bands.length===6)temp=requireColor(bands[5],"Temperature coefficient",TEMP_COLORS).temp;const significant=Number(digits.join("")),value=significant*10**multiplier,low=value*(1-tolerance/100),high=value*(1+tolerance/100);return{bands,significant,digits,multiplier,multiplierColor,tolerance,toleranceColor,temp,value,low,high};}
export function reverseLookup(value,bandCount=4,{toleranceColor="gold",tempColor="brown"}={}){const target=Number(value);if(!Number.isFinite(target)||target<=0)throw new Error("Resistance must be a positive number of ohms.");if(![4,5,6].includes(Number(bandCount)))throw new Error("Band count must be 4, 5, or 6.");const digitsNeeded=Number(bandCount)===4?2:3;for(let exponent=-2;exponent<=9;exponent+=1){const significant=target/10**exponent,rounded=Math.round(significant);if(Math.abs(significant-rounded)>Math.max(1e-9,Math.abs(significant)*1e-10))continue;if(rounded<10**(digitsNeeded-1)||rounded>=10**digitsNeeded)continue;const colors=String(rounded).split("").map(digit=>DIGIT_COLORS[Number(digit)]),multiplier=MULTIPLIER_COLORS.find(color=>COLORS[color].multiplier===exponent);if(!multiplier)continue;const bands=[...colors,multiplier,toleranceColor];if(Number(bandCount)===6)bands.push(tempColor);return{bands,result:calculate(bands)};}throw new Error(`No exact ${bandCount}-band color representation is available for ${target} Ω with supported multipliers.`);}
export function nearestE12(value){const target=Number(value);if(!Number.isFinite(target)||target<=0)throw new Error("Resistance must be positive.");let best=null;for(let decade=-2;decade<=9;decade+=1)for(const base of E12){const candidate=base*10**decade,error=Math.abs(candidate-target)/target;if(!best||error<best.relativeError)best={value:candidate,relativeError:error};}return best;}
export function explanation(result){const digits=result.digits.join(""),power=result.multiplier;return[`Read the significant color bands as ${digits}.`,`Apply the ${result.multiplierColor} multiplier: ${digits} × 10^${power} = ${formatOhms(result.value)}.`,`The ${result.toleranceColor} tolerance is ±${result.tolerance}%, giving ${formatOhms(result.low)} to ${formatOhms(result.high)}.`,result.temp===null?"This 4- or 5-band code does not include a temperature coefficient band.":`The final band gives a temperature coefficient of ${result.temp} ppm/°C.`];}
